CXX = g++
CXXFLAGS = -std=c++20 -O2 -Wall -Wextra -pedantic
TARGET = fit_distributions
SOURCES = main.cpp \
          stats.cpp \
          normal.cpp \
          laplace.cpp \
          hyperbolic_sech.cpp \
          logistic.cpp \
          model_registry.cpp \
          simulation.cpp \
          student_t.cpp \
          generalized_error.cpp \
          symmetric_hyperbolic.cpp
OBJECTS = $(SOURCES:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)
